#if defined(__APPLE__)
#define _DARWIN_C_SOURCE
#endif
#define _POSIX_C_SOURCE 200809L

#include "TCSession.h"

#include <errno.h>
#include <fcntl.h>
#include <poll.h>
#include <pthread.h>
#include <signal.h>
#include <spawn.h>
#include <stdbool.h>
#include <stdatomic.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/wait.h>

extern char **environ;

/*
 * The normal watchdog values are deliberately conservative.  A capture
 * preflight is allowed 25 seconds in total and every worker phase must make
 * progress at least once every eight seconds.  Fake workers use the shorter
 * values below so failure-path tests do not have to wait for production
 * timeouts.  A healthy fake worker pulses every 250ms and is therefore not
 * affected by the shorter interval.
 */
enum {
    TC_NORMAL_HEARTBEAT_MS = 8000,
    TC_NORMAL_PRECAPTURE_MS = 25000,
    TC_FAKE_HEARTBEAT_MS = 700,
    TC_FAKE_PRECAPTURE_MS = 2500,
    TC_CANCEL_GRACE_MS = 500
};

enum { TC_WORKER_EXIT_PARENT_GONE = 26 };

struct TCSession {
    pthread_mutex_t lock;

    char *exe;
    char *fake_mode;
    void (*on_event)(const char *, int, void *);
    void *ctx;

    pid_t pid;
    int control_write_fd;
    int status_read_fd;

    pthread_t monitor_thread;
    bool monitor_started;
    bool monitor_done;
    bool monitor_joining;
    bool start_in_progress;
    bool active;
    bool cancel_requested;
    bool timeout_reported;
    bool kill_sent;
    int64_t cancel_deadline_ms;

    char state;
    int64_t phase_started_ms;
    int64_t last_heartbeat_ms;
};

/* State used only in a worker process.  The worker never shares this memory
 * with its parent after posix_spawn. */
static int g_worker_control_fd = TC_WORKER_CONTROL_FD;
static int g_worker_status_fd = TC_WORKER_STATUS_FD;
static pthread_t g_worker_guard_thread;
static _Atomic int g_worker_guard_started;

static int64_t monotonic_millis(void) {
    struct timespec ts;
    if (clock_gettime(CLOCK_MONOTONIC, &ts) != 0) {
        /* CLOCK_MONOTONIC is required by the target macOS versions.  This
         * fallback keeps the test helper usable on older POSIX hosts. */
        return 0;
    }
    return (int64_t)ts.tv_sec * 1000 + ts.tv_nsec / 1000000;
}

static void close_fd(int *fd) {
    if (!fd || *fd < 0) return;
    int saved = errno;
    (void)close(*fd);
    *fd = -1;
    errno = saved;
}

/* A pipe write raises SIGPIPE before returning EPIPE when its reader has
 * gone away.  F_SETNOSIGPIPE is per-descriptor on Darwin; the signal-mask
 * fallback keeps this source usable on POSIX hosts without changing the
 * process-wide SIGPIPE disposition. */
static ssize_t write_without_sigpipe(int fd, const void *buffer, size_t length) {
#ifdef F_SETNOSIGPIPE
    if (fcntl(fd, F_SETNOSIGPIPE, 1) == 0) {
        ssize_t result;
        do {
            result = write(fd, buffer, length);
        } while (result < 0 && errno == EINTR);
        return result;
    }
#endif

    sigset_t pipe_set;
    sigset_t old_mask;
    sigset_t pending_before;
    if (sigemptyset(&pipe_set) != 0 || sigaddset(&pipe_set, SIGPIPE) != 0) {
        errno = EINVAL;
        return -1;
    }
    int mask_result = pthread_sigmask(SIG_BLOCK, &pipe_set, &old_mask);
    if (mask_result != 0) {
        errno = mask_result;
        return -1;
    }

    bool was_pending = sigpending(&pending_before) == 0 &&
                       sigismember(&pending_before, SIGPIPE) == 1;
    ssize_t result;
    do {
        result = write(fd, buffer, length);
    } while (result < 0 && errno == EINTR);
    int saved_errno = errno;

    /* A blocked SIGPIPE generated by this write is thread-directed.  Consume
     * only a newly pending instance before restoring the caller's mask; an
     * older pending signal belongs to the caller and must be preserved. */
    if (result < 0 && saved_errno == EPIPE && !was_pending) {
        sigset_t pending_after;
        if (sigpending(&pending_after) == 0 &&
            sigismember(&pending_after, SIGPIPE) == 1) {
            int received_signal = 0;
            (void)sigwait(&pipe_set, &received_signal);
        }
    }

    int restore_result = pthread_sigmask(SIG_SETMASK, &old_mask, NULL);
    if (restore_result != 0 && result >= 0) {
        result = -1;
        saved_errno = restore_result;
    }
    errno = saved_errno;
    return result;
}

static int set_cloexec(int fd) {
    int flags = fcntl(fd, F_GETFD, 0);
    if (flags < 0) return -1;
    return fcntl(fd, F_SETFD, flags | FD_CLOEXEC);
}

static int set_nonblocking(int fd) {
    int flags = fcntl(fd, F_GETFL, 0);
    if (flags < 0) return -1;
    return fcntl(fd, F_SETFL, flags | O_NONBLOCK);
}

static char *copy_string(const char *value) {
    if (!value) return NULL;
    size_t length = strlen(value);
    char *copy = (char *)malloc(length + 1);
    if (!copy) return NULL;
    memcpy(copy, value, length + 1);
    return copy;
}

static bool valid_state(char state) {
    return state == 'P' || state == 'E' || state == 'S' ||
           state == 'O' || state == 'L' || state == 'F';
}

static bool state_has_precapture_deadline(char state) {
    return state == 'P';
}

static int timeout_for_session(const TCSession *session, bool heartbeat) {
    if (session->fake_mode) {
        return heartbeat ? TC_FAKE_HEARTBEAT_MS : TC_FAKE_PRECAPTURE_MS;
    }
    return heartbeat ? TC_NORMAL_HEARTBEAT_MS : TC_NORMAL_PRECAPTURE_MS;
}

static int read_status_bytes(TCSession *session, char *buffer, size_t capacity) {
    int fd;
    pthread_mutex_lock(&session->lock);
    fd = session->status_read_fd;
    pthread_mutex_unlock(&session->lock);
    if (fd < 0 || capacity == 0) return 0;

    size_t used = 0;
    while (used < capacity) {
        ssize_t count = read(fd, buffer + used, capacity - used);
        if (count > 0) {
            used += (size_t)count;
            continue;
        }
        if (count == 0) break;
        if (errno == EINTR) continue;
        if (errno == EAGAIN || errno == EWOULDBLOCK) break;
        break;
    }
    return (int)used;
}

static int wait_child_locked(TCSession *session, int *wait_status) {
    if (session->pid <= 0) return 0;
    pid_t expected = session->pid;
    pid_t result;
    do {
        result = waitpid(expected, wait_status, WNOHANG);
    } while (result < 0 && errno == EINTR);

    if (result == expected) return 1;
    if (result < 0 && errno == ECHILD) {
        /* Another component reaped a pid that belongs to this session.  Do
         * not ever retry kill against a possibly reused pid. */
        return -1;
    }
    return 0;
}

static void kill_worker_locked(TCSession *session) {
    if (session->pid <= 0 || session->kill_sent) return;
    int result = kill(session->pid, SIGKILL);
    if (result == 0 || errno == ESRCH) session->kill_sent = true;
}

static int exit_value_from_wait_status(int wait_status) {
    if (WIFEXITED(wait_status)) return WEXITSTATUS(wait_status);
    if (WIFSIGNALED(wait_status)) return 128 + WTERMSIG(wait_status);
    return 255;
}

static void *monitor_main(void *argument) {
    TCSession *session = (TCSession *)argument;
    int child_wait_status = 0;
    bool child_reaped = false;
    int child_exit_value = 255;
    bool child_wait_error = false;

    pthread_mutex_lock(&session->lock);
    pid_t worker_pid = session->pid;
    void (*callback)(const char *, int, void *) = session->on_event;
    void *callback_context = session->ctx;
    session->state = 'P';
    session->phase_started_ms = monotonic_millis();
    session->last_heartbeat_ms = session->phase_started_ms;
    pthread_mutex_unlock(&session->lock);

    if (callback) callback("spawn", (int)worker_pid, callback_context);

    for (;;) {
        int status_fd;
        pthread_mutex_lock(&session->lock);
        status_fd = session->status_read_fd;
        pthread_mutex_unlock(&session->lock);

        struct pollfd descriptor = {.fd = status_fd, .events = POLLIN | POLLHUP | POLLERR};
        int poll_result;
        do {
            poll_result = poll(status_fd >= 0 ? &descriptor : NULL,
                               status_fd >= 0 ? 1 : 0, 50);
        } while (poll_result < 0 && errno == EINTR);

        if (poll_result > 0 && (descriptor.revents & (POLLIN | POLLHUP | POLLERR))) {
            char states[128];
            int count = read_status_bytes(session, states, sizeof(states));
            for (int i = 0; i < count; i++) {
                char state = states[i];
                if (!valid_state(state)) continue;
                int64_t now = monotonic_millis();
                pthread_mutex_lock(&session->lock);
                if (state != session->state) session->phase_started_ms = now;
                session->state = state;
                session->last_heartbeat_ms = now;
                callback = session->on_event;
                callback_context = session->ctx;
                pthread_mutex_unlock(&session->lock);
                if (callback) callback("state", (int)(unsigned char)state, callback_context);
            }
        }

        bool should_report_timeout = false;
        int timeout_code = 0;
        bool should_wait = false;
        int64_t now = monotonic_millis();

        pthread_mutex_lock(&session->lock);
        if (!child_reaped && !child_wait_error) {
            int wait_result = wait_child_locked(session, &child_wait_status);
            if (wait_result == 1) {
                child_reaped = true;
                child_exit_value = exit_value_from_wait_status(child_wait_status);
            } else if (wait_result < 0) {
                child_wait_error = true;
                child_reaped = true;
                child_exit_value = 255;
            }
        }

        if (!child_reaped && !child_wait_error) {
            if (session->cancel_requested &&
                now >= session->cancel_deadline_ms && !session->kill_sent) {
                kill_worker_locked(session);
                if (!session->timeout_reported) {
                    session->timeout_reported = true;
                    should_report_timeout = true;
                    timeout_code = TC_SESSION_TIMEOUT_CANCEL_KILL;
                }
            } else if (!session->cancel_requested && !session->timeout_reported) {
                int heartbeat_limit = timeout_for_session(session, true);
                int64_t heartbeat_age = now - session->last_heartbeat_ms;
                int64_t phase_age = now - session->phase_started_ms;
                if (heartbeat_age >= heartbeat_limit) {
                    kill_worker_locked(session);
                    session->timeout_reported = true;
                    should_report_timeout = true;
                    timeout_code = TC_SESSION_TIMEOUT_HEARTBEAT;
                } else if (state_has_precapture_deadline(session->state) &&
                           phase_age >= timeout_for_session(session, false)) {
                    kill_worker_locked(session);
                    session->timeout_reported = true;
                    should_report_timeout = true;
                    timeout_code = TC_SESSION_TIMEOUT_PRECAPTURE;
                }
            }
        }
        should_wait = child_reaped || child_wait_error;
        callback = session->on_event;
        callback_context = session->ctx;
        pthread_mutex_unlock(&session->lock);

        if (should_report_timeout && callback) {
            callback("timeout", timeout_code, callback_context);
        }
        if (should_wait) break;
    }

    int control_fd;
    int status_fd;
    pthread_mutex_lock(&session->lock);
    control_fd = session->control_write_fd;
    status_fd = session->status_read_fd;
    session->control_write_fd = -1;
    session->status_read_fd = -1;
    session->active = false;
    session->pid = 0;
    session->monitor_done = true;
    callback = session->on_event;
    callback_context = session->ctx;
    pthread_mutex_unlock(&session->lock);

    close_fd(&control_fd);
    close_fd(&status_fd);

    if (callback) callback("exit", child_exit_value, callback_context);
    return NULL;
}

static int make_pipe_cloexec(int pair[2]) {
    if (pipe(pair) != 0) return -1;
    if (set_cloexec(pair[0]) != 0 || set_cloexec(pair[1]) != 0) {
        close_fd(&pair[0]);
        close_fd(&pair[1]);
        return -1;
    }
    return 0;
}

static int add_close_if_needed(posix_spawn_file_actions_t *actions, int fd,
                               int first, int second) {
    if (fd >= 0 && fd != first && fd != second) {
        return posix_spawn_file_actions_addclose(actions, fd);
    }
    return 0;
}

static int duplicate_cloexec_fd(int fd) {
#ifdef F_DUPFD_CLOEXEC
    int duplicate_with_flag = fcntl(fd, F_DUPFD_CLOEXEC, TC_WORKER_STATUS_FD + 1);
    if (duplicate_with_flag >= 0) return duplicate_with_flag;
    if (errno != EINVAL && errno != ENOSYS) return -1;
#endif
    int duplicate = fcntl(fd, F_DUPFD, TC_WORKER_STATUS_FD + 1);
    if (duplicate < 0) return -1;
    if (set_cloexec(duplicate) != 0) {
        int saved = errno;
        (void)close(duplicate);
        errno = saved;
        return -1;
    }
    return duplicate;
}

static int relocate_spawn_sources(int control_pair[2], int status_pair[2]) {
    int *sources[] = {
        &control_pair[0], &control_pair[1], &status_pair[0], &status_pair[1]
    };
    for (size_t i = 0; i < sizeof(sources) / sizeof(sources[0]); i++) {
        int source = *sources[i];
        if (source < 0 ||
            (source != TC_WORKER_CONTROL_FD && source != TC_WORKER_STATUS_FD)) {
            continue;
        }
        int duplicate = duplicate_cloexec_fd(source);
        if (duplicate < 0) return errno;
        close_fd(sources[i]);
        *sources[i] = duplicate;
    }
    return 0;
}

static int spawn_worker(TCSession *session, int control_pair[2], int status_pair[2],
                        pid_t *worker_pid) {
    posix_spawn_file_actions_t actions;
    posix_spawnattr_t attributes;
    bool actions_initialized = false;
    bool attributes_initialized = false;
    int result = posix_spawn_file_actions_init(&actions);
    if (result != 0) goto cleanup;
    actions_initialized = true;

    /* dup2 replaces any pre-existing target descriptor.  Move every source
     * away from 198/199 first so a source is never closed by another dup2. */
    result = relocate_spawn_sources(control_pair, status_pair);
    if (result != 0) goto cleanup;
    result = posix_spawn_file_actions_adddup2(&actions, control_pair[0], TC_WORKER_CONTROL_FD);
    if (result != 0) goto cleanup;
    result = posix_spawn_file_actions_adddup2(&actions, status_pair[1], TC_WORKER_STATUS_FD);
    if (result != 0) goto cleanup;

    result = add_close_if_needed(&actions, control_pair[1],
                                TC_WORKER_CONTROL_FD, TC_WORKER_STATUS_FD);
    if (result != 0) goto cleanup;
    result = add_close_if_needed(&actions, status_pair[0],
                                TC_WORKER_CONTROL_FD, TC_WORKER_STATUS_FD);
    if (result != 0) goto cleanup;
    result = add_close_if_needed(&actions, control_pair[0],
                                TC_WORKER_CONTROL_FD, TC_WORKER_STATUS_FD);
    if (result != 0) goto cleanup;
    result = add_close_if_needed(&actions, status_pair[1],
                                TC_WORKER_CONTROL_FD, TC_WORKER_STATUS_FD);
    if (result != 0) goto cleanup;

    result = posix_spawnattr_init(&attributes);
    if (result != 0) goto cleanup;
    attributes_initialized = true;
#ifdef POSIX_SPAWN_CLOEXEC_DEFAULT
    result = posix_spawnattr_setflags(&attributes, POSIX_SPAWN_CLOEXEC_DEFAULT);
    if (result != 0) goto cleanup;
#endif

    char *argv[4] = {0};
    argv[0] = session->exe;
    if (session->fake_mode) {
        argv[1] = (char *)"--fake-worker";
        argv[2] = session->fake_mode;
    } else {
        argv[1] = (char *)"--capture-worker";
    }
    result = posix_spawn(worker_pid, session->exe, &actions, &attributes, argv, environ);

cleanup:
    if (attributes_initialized) (void)posix_spawnattr_destroy(&attributes);
    if (actions_initialized) (void)posix_spawn_file_actions_destroy(&actions);
    return result;
}

TCSession *TCSessionCreate(const char *exe,
                           const char *fakeMode,
                           void (*onEvent)(const char *, int, void *),
                           void *ctx) {
    if (!exe || !*exe) {
        errno = EINVAL;
        return NULL;
    }
    TCSession *session = (TCSession *)calloc(1, sizeof(*session));
    if (!session) return NULL;
    session->exe = copy_string(exe);
    session->fake_mode = copy_string(fakeMode);
    if (!session->exe || (fakeMode && !session->fake_mode)) {
        free(session->exe);
        free(session->fake_mode);
        free(session);
        return NULL;
    }
    if (pthread_mutex_init(&session->lock, NULL) != 0) {
        free(session->exe);
        free(session->fake_mode);
        free(session);
        errno = EAGAIN;
        return NULL;
    }
    session->pid = 0;
    session->control_write_fd = -1;
    session->status_read_fd = -1;
    session->on_event = onEvent;
    session->ctx = ctx;
    return session;
}

int TCSessionStart(TCSession *session) {
    if (!session) {
        errno = EINVAL;
        return -1;
    }

    pthread_t old_monitor;
    bool join_old = false;
    pthread_mutex_lock(&session->lock);
    if (session->active || session->start_in_progress || session->monitor_joining) {
        pthread_mutex_unlock(&session->lock);
        errno = EBUSY;
        return -1;
    }
    if (session->monitor_started) {
        if (!session->monitor_done) {
            pthread_mutex_unlock(&session->lock);
            errno = EBUSY;
            return -1;
        }
        old_monitor = session->monitor_thread;
        session->monitor_joining = true;
        join_old = true;
    }
    pthread_mutex_unlock(&session->lock);

    if (join_old) {
        int join_result = pthread_join(old_monitor, NULL);
        pthread_mutex_lock(&session->lock);
        session->monitor_joining = false;
        session->monitor_started = false;
        session->monitor_done = false;
        pthread_mutex_unlock(&session->lock);
        if (join_result != 0) {
            errno = join_result;
            return -1;
        }
    }

    int control_pair[2] = {-1, -1};
    int status_pair[2] = {-1, -1};
    if (make_pipe_cloexec(control_pair) != 0 || make_pipe_cloexec(status_pair) != 0) {
        close_fd(&control_pair[0]);
        close_fd(&control_pair[1]);
        close_fd(&status_pair[0]);
        close_fd(&status_pair[1]);
        return -1;
    }
    if (set_nonblocking(status_pair[0]) != 0) {
        close_fd(&control_pair[0]);
        close_fd(&control_pair[1]);
        close_fd(&status_pair[0]);
        close_fd(&status_pair[1]);
        return -1;
    }

    pthread_mutex_lock(&session->lock);
    if (session->active || session->start_in_progress) {
        pthread_mutex_unlock(&session->lock);
        close_fd(&control_pair[0]);
        close_fd(&control_pair[1]);
        close_fd(&status_pair[0]);
        close_fd(&status_pair[1]);
        errno = EBUSY;
        return -1;
    }
    session->start_in_progress = true;
    pthread_mutex_unlock(&session->lock);

    pid_t worker_pid = 0;
    int spawn_result = spawn_worker(session, control_pair, status_pair, &worker_pid);
    close_fd(&control_pair[0]);
    close_fd(&status_pair[1]);
    if (spawn_result != 0) {
        close_fd(&control_pair[1]);
        close_fd(&status_pair[0]);
        pthread_mutex_lock(&session->lock);
        session->start_in_progress = false;
        pthread_mutex_unlock(&session->lock);
        errno = spawn_result;
        return -1;
    }

    pthread_mutex_lock(&session->lock);
    session->pid = worker_pid;
    session->control_write_fd = control_pair[1];
    session->status_read_fd = status_pair[0];
    session->cancel_requested = false;
    session->timeout_reported = false;
    session->kill_sent = false;
    session->cancel_deadline_ms = 0;
    session->state = 'P';
    session->phase_started_ms = monotonic_millis();
    session->last_heartbeat_ms = session->phase_started_ms;
    session->active = true;
    session->monitor_done = false;
    int thread_result = pthread_create(&session->monitor_thread, NULL, monitor_main, session);
    if (thread_result != 0) {
        session->active = false;
        session->pid = 0;
        session->control_write_fd = -1;
        session->status_read_fd = -1;
        session->start_in_progress = false;
        pthread_mutex_unlock(&session->lock);
        (void)kill(worker_pid, SIGKILL);
        int ignored_status;
        while (waitpid(worker_pid, &ignored_status, 0) < 0 && errno == EINTR) {}
        close_fd(&control_pair[1]);
        close_fd(&status_pair[0]);
        errno = thread_result;
        return -1;
    }
    session->monitor_started = true;
    session->start_in_progress = false;
    pthread_mutex_unlock(&session->lock);
    return 0;
}

void TCSessionCancel(TCSession *session) {
    if (!session) return;
    pthread_mutex_lock(&session->lock);
    if (!session->active || session->pid <= 0 || session->cancel_requested) {
        pthread_mutex_unlock(&session->lock);
        return;
    }
    session->cancel_requested = true;
    session->cancel_deadline_ms = monotonic_millis() + TC_CANCEL_GRACE_MS;
    int fd = session->control_write_fd;
    if (fd >= 0) {
        char command = 'C';
        (void)write_without_sigpipe(fd, &command, 1);
    }
    pthread_mutex_unlock(&session->lock);
}

int TCSessionIsActive(TCSession *session) {
    if (!session) return 0;
    pthread_mutex_lock(&session->lock);
    int active = session->active ? 1 : 0;
    pthread_mutex_unlock(&session->lock);
    return active;
}

void TCSessionDestroy(TCSession *session) {
    if (!session) return;
    TCSessionCancel(session);

    pthread_t monitor;
    bool join_monitor = false;
    pthread_mutex_lock(&session->lock);
    if (session->monitor_started && !session->monitor_joining &&
        !pthread_equal(pthread_self(), session->monitor_thread)) {
        monitor = session->monitor_thread;
        session->monitor_joining = true;
        join_monitor = true;
    }
    pthread_mutex_unlock(&session->lock);
    if (join_monitor) {
        (void)pthread_join(monitor, NULL);
        pthread_mutex_lock(&session->lock);
        session->monitor_started = false;
        session->monitor_joining = false;
        pthread_mutex_unlock(&session->lock);
    }

    pthread_mutex_lock(&session->lock);
    int control_fd = session->control_write_fd;
    int status_fd = session->status_read_fd;
    session->control_write_fd = -1;
    session->status_read_fd = -1;
    pthread_mutex_unlock(&session->lock);
    close_fd(&control_fd);
    close_fd(&status_fd);

    pthread_mutex_destroy(&session->lock);
    free(session->exe);
    free(session->fake_mode);
    free(session);
}

static void worker_exit_now(int code) {
    if (code < 0) code = 255;
    if (code > 255) code &= 255;
    _exit(code);
}

static void *worker_guard_main(void *unused) {
    (void)unused;
    struct pollfd descriptor = {
        .fd = g_worker_control_fd,
        .events = POLLIN | POLLHUP | POLLERR
    };
    for (;;) {
        int result;
        do {
            result = poll(&descriptor, 1, -1);
        } while (result < 0 && errno == EINTR);
        if (result < 0) worker_exit_now(TC_WORKER_EXIT_PARENT_GONE);
        if (descriptor.revents & (POLLERR | POLLNVAL | POLLHUP)) {
            char command;
            ssize_t count = read(g_worker_control_fd, &command, 1);
            if (count <= 0) worker_exit_now(TC_WORKER_EXIT_PARENT_GONE);
            if (command == 'C') worker_exit_now(TC_WORKER_EXIT_CANCELLED);
        }
        if (descriptor.revents & POLLIN) {
            char commands[32];
            ssize_t count;
            do {
                count = read(g_worker_control_fd, commands, sizeof(commands));
            } while (count < 0 && errno == EINTR);
            if (count == 0) worker_exit_now(TC_WORKER_EXIT_PARENT_GONE);
            if (count < 0) {
                if (errno == EAGAIN || errno == EWOULDBLOCK) continue;
                worker_exit_now(TC_WORKER_EXIT_PARENT_GONE);
            }
            for (ssize_t i = 0; i < count; i++) {
                if (commands[i] == 'C') worker_exit_now(TC_WORKER_EXIT_CANCELLED);
            }
        }
    }
}

int TCWorkerGuardStart(void) {
    if (atomic_exchange(&g_worker_guard_started, 1)) return 0;
    if (fcntl(g_worker_control_fd, F_GETFD, 0) < 0 ||
        fcntl(g_worker_status_fd, F_GETFD, 0) < 0) {
        atomic_store(&g_worker_guard_started, 0);
        return -1;
    }
    int result = pthread_create(&g_worker_guard_thread, NULL, worker_guard_main, NULL);
    if (result != 0) {
        atomic_store(&g_worker_guard_started, 0);
        errno = result;
        return -1;
    }
    (void)pthread_detach(g_worker_guard_thread);
    return 0;
}

void TCWorkerPulse(char state) {
    if (!valid_state(state)) return;
    char value = state;
    (void)write_without_sigpipe(g_worker_status_fd, &value, 1);
    /* EPIPE means the parent has already gone away.  The guard thread will
     * observe control-pipe EOF and terminate the process independently. */
}

void TCWorkerFinish(int exitCode) {
    int status_fd = g_worker_status_fd;
    g_worker_status_fd = -1;
    close_fd(&status_fd);
    worker_exit_now(exitCode);
}

static void sleep_millis(int milliseconds) {
    struct timespec request = {
        .tv_sec = milliseconds / 1000,
        .tv_nsec = (long)(milliseconds % 1000) * 1000000L
    };
    while (nanosleep(&request, &request) != 0 && errno == EINTR) {}
}

static void fake_pulse_for(char state, int duration_ms) {
    int elapsed = 0;
    while (elapsed < duration_ms) {
        TCWorkerPulse(state);
        int step = duration_ms - elapsed;
        if (step > 200) step = 200;
        sleep_millis(step);
        elapsed += step;
    }
}

int TCSessionRunFakeWorker(const char *mode) {
    if (!mode) mode = "success";
    if (strcmp(mode, "reader-closed") == 0) {
        /* Deliberately leave the worker alive after closing only the control
         * reader.  The parent-side regression test then exercises a real
         * EPIPE in TCSessionCancel without involving a process-wide signal
         * handler. */
        close_fd(&g_worker_control_fd);
        for (;;) {
            TCWorkerPulse('E');
            sleep_millis(100);
        }
    }
    if (TCWorkerGuardStart() != 0) return 30;

    if (strcmp(mode, "success") == 0) {
        TCWorkerPulse('P');
        sleep_millis(40);
        TCWorkerPulse('E');
        sleep_millis(40);
        TCWorkerPulse('F');
        TCWorkerFinish(0);
    } else if (strcmp(mode, "cancel") == 0 || strcmp(mode, "parent") == 0 ||
               strcmp(mode, "healthy") == 0) {
        fake_pulse_for('E', 2000);
        TCWorkerFinish(0);
    } else if (strcmp(mode, "healthy-edit") == 0) {
        fake_pulse_for('E', 1600);
        TCWorkerFinish(0);
    } else if (strcmp(mode, "healthy-save") == 0) {
        fake_pulse_for('S', 1600);
        TCWorkerFinish(1);
    } else if (strcmp(mode, "healthy-ocr") == 0) {
        fake_pulse_for('O', 1600);
        TCWorkerFinish(2);
    } else if (strcmp(mode, "healthy-long") == 0) {
        fake_pulse_for('L', 1600);
        TCWorkerFinish(0);
    } else if (strcmp(mode, "crash") == 0) {
        TCWorkerPulse('P');
        _exit(26);
    } else if (strcmp(mode, "signal-crash") == 0) {
        TCWorkerPulse('P');
        raise(SIGABRT);
    } else if (strcmp(mode, "hang") == 0 || strcmp(mode, "hang-p") == 0) {
        TCWorkerPulse('P');
        for (;;) pause();
    } else if (strcmp(mode, "stop") == 0 || strcmp(mode, "hang-stop") == 0) {
        TCWorkerPulse('P');
        raise(SIGSTOP);
        for (;;) pause();
    } else if (strcmp(mode, "no_permission") == 0) {
        TCWorkerPulse('P');
        TCWorkerFinish(20);
    } else if (strcmp(mode, "capture_failure") == 0) {
        TCWorkerPulse('P');
        TCWorkerFinish(22);
    } else if (strcmp(mode, "abi_failure") == 0) {
        TCWorkerPulse('P');
        TCWorkerFinish(21);
    } else if (strcmp(mode, "save_cancel") == 0) {
        TCWorkerPulse('S');
        TCWorkerFinish(11);
    } else if (strcmp(mode, "ocr_empty") == 0) {
        TCWorkerPulse('O');
        TCWorkerFinish(12);
    } else if (strcmp(mode, "long_failure") == 0) {
        TCWorkerPulse('L');
        TCWorkerFinish(25);
    } else {
        TCWorkerPulse('P');
        TCWorkerFinish(23);
    }
    return 0;
}
